### ISSUE TITLE
License ambiguation: GPLv3 and notices

### ISSUE THREAD

**Issue by j8r** [elfoxero/file-manager#28]
It could be nice if file-manager has a "GPLv3 or later" clause to the license, especially for the future.

**Comment by JulR43** [comment]
The clause is already present in [LICENSE file](https://github.com/elfoxero/file-manager/blob/master/LICENSE.txt) "or (at your option) any later version." at line 640. Furthermore, the [notice at the begining of files like this one](https://github.com/elfoxero/file-manager/blob/master/index.html) doesn't match with the standard GPLv3 notice, it's a MIT notice. Therefore there are different options:
- replace MIT notices by a link to the GPLv3 license url, and specify in README the "or later" clause.
- keep MIT notices to have MIT licensed files, and change the app license to MPL or LGPL.
- or the most radical: change the app license from GPLv3 to MIT.

But now the problem is that File Manager is GPLv3 licensed, thus MIT notices are not very coherent :/ I will create a button to access through "About us" ;).
Finally i suggest a super simple:
```javascript
/*
 * File Manager - 
 * https://github.com/zhukov/webogram
 * Copyright (C) 2013-2015 Jhon Klever and contributors
 * https://github.com/elfoxero/file-manager/blob/master/LICENSE
 */
```

**Comment by JulR43** [comment]
In addition, this default notices is too long:
![capture d ecran_2015-05-25_20-51-07](https://cloud.githubusercontent.com/assets/6562667/7801490/99eea7fc-0325-11e5-87de-953784ad6b09.png)
I think that this notices is most appropriate:
```
File Manager - A Firefox OS file manager app
Copyright (C) 2013-2015 Jhon Klever

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

https://github.com/elfoxero/file-manager/blob/master/LICENSE
```
I'll create a new branch with this changes.
